import {Nunito} from 'next/font/google'
import { Metadata } from 'next/types'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>

      </body>
    </html>
  )
}
